# Generated by Django 3.2.13 on 2022-10-11 16:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnalis/'),
        ),
    ]
